backend:
  name: git-gateway
  branch: main

media_folder: "Artigos_e_Publicacoes/images/uploads"
public_folder: "/Artigos_e_Publicacoes/images/uploads"

collections:
  - name: "artigos"
    label: "Artigos"
    folder: "Artigos_e_Publicacoes/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de Publicação", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "string"}
      - {label: "Imagem de Capa", name: "image", widget: "image"}
      - {label: "Resumo", name: "description", widget: "text"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
